/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library(123456);
    assertTrue(
        "someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    System.out.println("Before Add");
    classUnderTest.Add(867-5309);
    assertTrue("found 867-5309", classUnderTest.Find(867-5309));
  }
}
