/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Library */

#ifndef _Included_Library
#define _Included_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Library
 * Method:    doNothing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Library_doNothing
  (JNIEnv *, jobject);

/*
 * Class:     Library
 * Method:    Allocate
 * Signature: (Ljava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_Library_Allocate
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     Library
 * Method:    FindDetail
 * Signature: (Ljava/nio/ByteBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_Library_FindDetail
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     Library
 * Method:    AddDetail
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_Library_AddDetail
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     Library
 * Method:    Deallocate
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_Library_Deallocate
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
