name: unit-tests

on: push

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install cffi
        make world
    - name: run C tests
      run: c/extras/test/paths.exe
    - name: run C++ tests
      run: cpp/extras/test/block.exe
    - name: run Java tests
      run: mvn -f ./java/ test
    - name: run golang tests
      run: |
        cd go
        go test
