name: C/C++ CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
