name: c-cpp

on:
  push:
    branches: [ ci-remote ]
  pull_request:
    branches: [ ci-remote ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      run: make all
