name: unit-tests

on: push

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: check C compiler exists
      run: gcc --version
    - name: check make version
      run: make --version
    - name: Add Msys64 to PATH
      if: matrix.os == 'windows-2019'
      run: |
        echo "/c/msys64/mingw64/bin" >> $GITHUB_PATH
        echo "/c/msys64/usr/bin" >> $GITHUB_PATH
        echo "$PATH"
      shell: bash
    - name: check C compiler exists
      run: cc --version
    - name: make
      run: make world
    - name: run C tests
      run: c/extras/test/paths.exe
    - name: run C++ tests
      run: cpp/extras/test/block.exe
    - name: run Java tests
      run: mvn -f ./java/ test
