name: c-cpp

on:
  push:
    branches: [ ci-remote ]
  pull_request:
    branches: [ ci-remote ]

jobs:
  build:

    matrix:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      run: make all
