name: c-cpp

on: push

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      run: make world
    - name: run C++ tests
      run: cpp/extras/test/block.exe
    - name: run Java tests
      run: mvn -f ./java/ test
