name: c-cpp

on: push

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: diagnostics
      run: cc --version
    - name: make
      run: make -k world
    - name: run tests
      run: cpp/extras/test/block.exe
